# Generated by Django 3.2.3 on 2021-06-07 23:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Pyme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField()),
                ('updated_date', models.DateTimeField()),
                ('deleted_date', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('name', models.CharField(max_length=70)),
                ('code', models.CharField(db_index=True, max_length=70)),
            ],
            options={
                'verbose_name': 'Pyme',
                'verbose_name_plural': 'Pymes',
            },
        ),
        migrations.CreateModel(
            name='PymeUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField()),
                ('updated_date', models.DateTimeField()),
                ('deleted_date', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('pyme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='users', to='pymes.pyme')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pyme_users', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Pyme User',
                'verbose_name_plural': 'Pyme Users',
                'unique_together': {('pyme', 'user')},
            },
        ),
    ]
