# Generated by Django 3.2.3 on 2021-06-19 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20210619_1053'),
    ]

    operations = [
        migrations.AddField(
            model_name='productpicture',
            name='picture',
            field=models.ImageField(default='', upload_to='productImages'),
            preserve_default=False,
        ),
    ]
